using System.Text;
using MkPFS.Core.Crypto;
using MkPFS.Core.Images;
using MkPFS.Core.IO;
using MkPFS.Core.Metadata;
using MkPFS.Core.PKG;
using MkPFS.Core.SELF;

namespace MkPFS.Build.FPKG;

/// <summary>Where a package input comes from.</summary>
public enum FPKGInputOrigin
{
    /// <summary>A source file, packed as is.</summary>
    Source,

    /// <summary>A plain ELF module from the source, fake-signed in memory.</summary>
    FakeSigned,

    /// <summary>Generated by <c>pack fpkg</c> (keystone, pfs-version.dat, right.sprx, param.json, DDS).</summary>
    Generated,
}

/// <summary>One package input: an inner file or a CNT entry.</summary>
public sealed class FPKGInput
{
    /// <summary>Inner path (<c>sce_sys/keystone</c>) or CNT entry name (<c>icon0.png</c>).</summary>
    public required string Path { get; init; }

    /// <summary>Origin.</summary>
    public required FPKGInputOrigin Origin { get; init; }

    /// <summary>Source file, for <see cref="FPKGInputOrigin.Source"/>.</summary>
    public string? SourceFile { get; init; }

    /// <summary>In-memory bytes, for converted or generated inputs.</summary>
    public byte[]? Data { get; init; }

    private long _size = -1;

    /// <summary>Size in bytes (a source file's is read once, on first use).</summary>
    public long Size => _size >= 0 ? _size : _size = Data?.LongLength ?? new FileInfo(SourceFile!).Length;

    /// <summary>Read the whole input.</summary>
    /// <returns>Bytes.</returns>
    public byte[] ReadAll() => Data ?? File.ReadAllBytes(SourceFile!);

    /// <summary>Open the input for reading.</summary>
    /// <returns>Read-only stream.</returns>
    public Stream Open() => Data is not null
        ? new MemoryStream(Data, writable: false)
        : new FileStream(SourceFile!, FileMode.Open, FileAccess.Read, FileShare.Read, 1 << 16, FileOptions.SequentialScan);
}

/// <summary>An executable module and how a debug-mode console treats it.</summary>
/// <param name="Path">Inner path.</param>
/// <param name="SourceKind">Kind in the source folder.</param>
/// <param name="PackedKind">Kind as packed (after fake-signing).</param>
public sealed record FPKGModule(string Path, ModuleKind SourceKind, ModuleKind PackedKind)
{
    /// <summary>Starts on a debug-mode console.</summary>
    public bool Runs => PackedKind == ModuleKind.FakeSELF;
}

/// <summary>Options for <see cref="FPKGSource.Prepare"/>.</summary>
public sealed class FPKGSourceOptions
{
    /// <summary>Source folder (an application root with <c>eboot.bin</c> and <c>sce_sys/</c>).</summary>
    public required string SourceDir { get; init; }

    /// <summary>36-character content id.</summary>
    public required string ContentId { get; init; }

    /// <summary>32-character passcode (keystone input).</summary>
    public string Passcode { get; init; } = new('0', PS5Keys.PasscodeLength);

    /// <summary>Title for a generated param.json.</summary>
    public string? Title { get; init; }

    /// <summary>Master version <c>NN.NN</c> for a generated param.json.</summary>
    public string Version { get; init; } = "01.00";

    /// <summary><c>applicationDrmType</c> for a generated param.json.</summary>
    public string DrmType { get; init; } = "free";

    /// <summary>Fake-sign plain ELF modules (default true).</summary>
    public bool FakeSign { get; init; } = true;

    /// <summary>Fake-SELF options.</summary>
    public FakeSELFOptions? FakeSELF { get; init; }
}

/// <summary>
/// The package view of a source folder: the inner files and CNT entries <c>pack fpkg</c> writes, with
/// modules fake-signed and missing system files generated in memory. The source folder is only read.
/// Layout rules follow Publishing Tools (<c>tools/oracle-fpkg/README.md</c> findings 8–9): non-ASCII
/// paths are refused, <c>sce_sys/pfs-version.dat</c> and <c>sce_sys/about/right.sprx</c> are added,
/// presentation files and system data become CNT entries, and <c>changeinfo/</c> stays an inner directory.
/// </summary>
public sealed class FPKGSource
{
    /// <summary>Embedded resource holding Publishing Tools' <c>sce_sys/about/right.sprx</c>.</summary>
    public const string RightSprxResource = "MkPFS.Build.FPKG.right.sprx";

    // sce_sys files the package builder generates; supplied copies are ignored (Publishing Tools does the same).
    private static readonly HashSet<string> BuilderGenerated = new(StringComparer.Ordinal)
    {
        "playgo-chunk.dat", "playgo-chunk.sha", "playgo-manifest.xml", "playgo-hash-table.dat",
        "playgo-ficm.dat", "playgo-scenario.json", "imagedigs.dat",
    };

    private FPKGSource(List<FPKGInput> inner, List<FPKGInput> entries, List<FPKGModule> modules, List<string> warnings, List<string> errors)
    {
        InnerFiles = inner;
        Entries = entries;
        Modules = modules;
        Warnings = warnings;
        Errors = errors;
    }

    /// <summary>Inner files, ordinal by path.</summary>
    public IReadOnlyList<FPKGInput> InnerFiles { get; }

    /// <summary>CNT entries from the source (param.json, media, system data), ordinal by name.</summary>
    public IReadOnlyList<FPKGInput> Entries { get; }

    /// <summary>Executable modules.</summary>
    public IReadOnlyList<FPKGModule> Modules { get; }

    /// <summary>Notes that do not stop a build.</summary>
    public IReadOnlyList<string> Warnings { get; }

    /// <summary>Problems that make the package unusable.</summary>
    public IReadOnlyList<string> Errors { get; }

    /// <summary>Embedded <c>right.sprx</c>.</summary>
    /// <returns>Bytes.</returns>
    public static byte[] RightSprx()
    {
        using Stream stream = typeof(FPKGSource).Assembly.GetManifestResourceStream(RightSprxResource)
            ?? throw new InvalidOperationException($"missing embedded resource {RightSprxResource}");
        using MemoryStream copy = new();
        stream.CopyTo(copy);
        return copy.ToArray();
    }

    /// <summary>Build the package view of <see cref="FPKGSourceOptions.SourceDir"/>.</summary>
    /// <param name="options">Options.</param>
    /// <returns>Inputs, module report, warnings and errors.</returns>
    /// <exception cref="DirectoryNotFoundException">The source folder does not exist.</exception>
    public static FPKGSource Prepare(FPKGSourceOptions options)
    {
        string root = Path.GetFullPath(options.SourceDir);
        if (!Directory.Exists(root))
        {
            throw new DirectoryNotFoundException($"source folder not found: {root}");
        }

        List<string> warnings = [];
        List<string> errors = [];
        SortedDictionary<string, FPKGInput> inner = new(StringComparer.Ordinal);
        SortedDictionary<string, FPKGInput> entries = new(StringComparer.Ordinal);
        List<FPKGModule> modules = [];

        // ---- Sort source files into inner files and CNT entries. ----
        foreach (string file in SourceScanner.GatherFiles(root))
        {
            string rel = Path.GetRelativePath(root, file).Replace(Path.DirectorySeparatorChar, '/');
            // Publishing Tools refuses non-ASCII paths; PS5PkgTool writes each such character as '?', which loses
            // the name (tools/oracle-ppt/README.md).
            if (!Ascii.IsValid(rel))
            {
                errors.Add($"non-ASCII path (Publishing Tools refuses it, PS5PkgTool mangles it): {rel}");
                continue;
            }

            if (rel.EndsWith(".gp4", StringComparison.OrdinalIgnoreCase) || rel.EndsWith(".gp5", StringComparison.OrdinalIgnoreCase))
            {
                warnings.Add($"skipped project file {rel}");
                continue;
            }

            FPKGInput source = new() { Path = rel, Origin = FPKGInputOrigin.Source, SourceFile = file };
            if (rel.StartsWith("sce_sys/", StringComparison.Ordinal))
            {
                string name = rel["sce_sys/".Length..];
                if (name == "param.sfo")
                {
                    errors.Add("sce_sys/param.sfo is a PS4 file; the PS5 launch service refuses it (remove it and supply param.json)");
                    continue;
                }

                if (BuilderGenerated.Contains(name))
                {
                    warnings.Add($"ignored {rel}: pack fpkg generates it");
                    continue;
                }

                // Files with a CNT id (changeinfo/ included) are CNT entries, not inner files (PS5PkgTool).
                if (CNTEntryNames.NameToId.ContainsKey(name))
                {
                    entries[name] = new FPKGInput { Path = name, Origin = FPKGInputOrigin.Source, SourceFile = file };
                    continue;
                }
            }

            inner[rel] = source;
        }

        // ---- param.json: supplied as is, or generated. ----
        if (!entries.TryGetValue("param.json", out FPKGInput? param))
        {
            try
            {
                param = new FPKGInput
                {
                    Path = "param.json",
                    Origin = FPKGInputOrigin.Generated,
                    Data = PS5ParamJson.Create(options.ContentId, options.Title, options.Version, options.DrmType),
                };
                entries["param.json"] = param;
                warnings.Add("generated sce_sys/param.json");
            }
            catch (ArgumentException ex)
            {
                errors.Add($"cannot generate sce_sys/param.json: {ex.Message}");
            }
        }

        // ---- Generated inner system files; supplied copies win. ----
        if (!inner.ContainsKey("sce_sys/keystone"))
        {
            inner["sce_sys/keystone"] = Generated("sce_sys/keystone", PS5Keys.Keystone(options.Passcode));
        }
        else if (inner["sce_sys/keystone"].Size != PS5Keys.KeystoneSize)
        {
            errors.Add($"sce_sys/keystone must be {PS5Keys.KeystoneSize} bytes");
        }

        if (!inner.ContainsKey("sce_sys/pfs-version.dat"))
        {
            string version = (param is null ? null : PS5ParamJson.ReadContentVersion(param.ReadAll()))
                ?? PS5ParamJson.ContentVersion(options.Version);
            inner["sce_sys/pfs-version.dat"] = Generated("sce_sys/pfs-version.dat", Encoding.ASCII.GetBytes(version));
        }

        if (!inner.ContainsKey("sce_sys/about/right.sprx"))
        {
            inner["sce_sys/about/right.sprx"] = Generated("sce_sys/about/right.sprx", RightSprx());
        }

        // ---- Presentation DDS from PNG, unless supplied. ----
        foreach ((string png, string dds) in CNTEntryNames.DdsMedia)
        {
            if (entries.TryGetValue(png, out FPKGInput? image) && !entries.ContainsKey(dds))
            {
                try
                {
                    entries[dds] = new FPKGInput { Path = dds, Origin = FPKGInputOrigin.Generated, Data = DDSEncoder.EncodePngToDds(image.ReadAll()) };
                }
                catch (Exception ex) when (ex is InvalidDataException or ArgumentException)
                {
                    errors.Add($"sce_sys/{png} is not a usable PNG: {ex.Message}");
                }
            }
        }

        // ---- Modules: fake-sign plain ELFs, report the rest. ----
        foreach (FPKGInput input in inner.Values.ToList())
        {
            if (input.Origin != FPKGInputOrigin.Source || !ModuleClassifier.IsModuleName(input.Path))
            {
                continue;
            }

            byte[] data = input.ReadAll();
            ModuleKind kind = ModuleClassifier.Classify(data).Kind;
            if (kind == ModuleKind.NotExecutable)
            {
                continue;
            }

            ModuleKind packed = kind;
            if (kind == ModuleKind.RawELF && options.FakeSign)
            {
                try
                {
                    inner[input.Path] = new FPKGInput { Path = input.Path, Origin = FPKGInputOrigin.FakeSigned, SourceFile = input.SourceFile, Data = SELFFile.MakeFake(data, options.FakeSELF) };
                    packed = ModuleKind.FakeSELF;
                }
                catch (ArgumentException ex)
                {
                    errors.Add($"{input.Path}: cannot fake-sign: {ex.Message}");
                }
            }

            FPKGModule module = new(input.Path, kind, packed);
            modules.Add(module);
            if (!module.Runs)
            {
                errors.Add($"{input.Path} will not start on a debug-mode console ({packed})");
            }
        }

        if (!inner.ContainsKey("eboot.bin"))
        {
            errors.Add("no eboot.bin at the application root");
        }

        return new FPKGSource([.. inner.Values], [.. entries.Values], modules, warnings, errors);
    }

    private static FPKGInput Generated(string path, byte[] data) => new() { Path = path, Origin = FPKGInputOrigin.Generated, Data = data };
}
